variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  tags:
    - shell
  script:
    - make
  artifacts:
    paths:
      - ./*.ko
    expire_in: 1h

.test:
  stage: test
  tags:
    - shell
  script:
    - true

.push_github:
    stage: deploy
    script:
        - git remote add github https://$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_USERNAME/$CI_PROJECT_NAME.git || true
        # we need some extra treatment because the gitlab-runner doesn't check out the full history
        - git push github HEAD:master --tags
